const adjectives = [
  'abandoned',
  'alien',
  'Amazonian',
  'ancient',
  'arid',
  'barren',
  'beautiful',
  'big',
  'bland',
  'bleak',
  'blessed',
  'blighted',
  'blood-stained',
  'boring',
  'bright',
  'brisk',
  'bustling',
  'busy',
  'buttery',
  'cavernous',
  'chilly',
  'Chinese',
  'clean',
  'cloudy',
  'cluttered',
  'collapsing',
  'colorful',
  'complicated',
  'confusing',
  'constantly-changing',
  'corrupted',
  'creatively arranged',
  'crumbling',
  'damp',
  'dangerous',
  'dark',
  'deliberately placed',
  'deserted',
  'destroyed',
  'deteriorating',
  'diamond-encrusted',
  'digital',
  'dingy',
  'dirty',
  'disappearing',
  'disgusting',
  'dismal',
  'distant',
  'drab',
  'drafty',
  'dreary',
  'dystopian',
  'edible',
  'eerie',
  'Egyptian',
  'elaborately detailed',
  'empty',
  'enchanted',
  'enchanting',
  'enormous',
  'enshrouded',
  'expansive',
  'falling',
  'far-off',
  'faraway',
  'fearfully constructed',
  'fiery',
  'filthy',
  'flaming',
  'flawless',
  'flimsy',
  'floating',
  'fog-shrouded',
  'French',
  'frightening',
  'frozen',
  'ghostly',
  'gilded',
  'gloomy',
  'glorious',
  'golden',
  'grand',
  'grandiose',
  'gray',
  'Greek',
  'grim',
  'grimy',
  'haunted',
  'hidden',
  'hilly',
  'hilly',
  'historically accurate',
  'holy',
  'hope-filled',
  'horrible',
  'horrifying',
  'huge',
  'imaginary',
  'immaculate',
  'immaterial',
  'immense',
  'impenetrable',
  'important',
  'Incan',
  'incomprehensible',
  'incredible',
  'Indian',
  'Internet-based',
  'Italian',
  'Japanese',
  'jewel-encrusted',
  'Korean',
  'lavish',
  'levitating',
  'little',
  'living',
  'lonely',
  'lustrous',
  'luxurious',
  'Mayan',
  'messy',
  'meticulously arranged',
  'microscopic',
  'modern',
  'monumental',
  'mountainous',
  'muddy',
  'murky',
  'mysterious',
  'Napoleonic',
  'newly built',
  'newly made',
  'nippy',
  'noisy',
  'old-fashioned',
  'ominous',
  'opulent',
  'orderly',
  'ordinary',
  'ornate',
  'outlying',
  'pagan',
  'parched',
  'photorealistic',
  'plagued',
  'planked',
  'plastic',
  'platinum',
  'pleasant',
  'plush',
  'posh',
  'quaint',
  'quilted',
  'rancid',
  'remote',
  'restored',
  'Roman',
  'rotten',
  'rotting',
  'ruby-encrusted',
  'rundown',
  'Russian',
  'safe',
  'sandy',
  'secret',
  'serene',
  'shabby',
  'shadowy',
  'shady',
  'shifting',
  'shimmering',
  'shining',
  'shiny',
  'slippery',
  'small',
  'smelly',
  'smoggy',
  'smoking',
  'smoldering',
  'sparse',
  'spinning',
  'splintered',
  'stone',
  'stony',
  'stormy',
  'submerged',
  'suburban',
  'sunny',
  'suspicious',
  'suspiciously clean',
  'suspiciously dark',
  'suspiciously dreary',
  'swampy',
  'sweltering',
  'terrifying',
  'tumultuous',
  'twisted',
  'ugly',
  'unbearably dry',
  'unbearably swampy',
  'underwater',
  'unholy',
  'urban',
  'vast',
  'vibrant',
  'virtual',
  'vivid',
  'walking',
  'watery',
  'well-lit',
  'well-made',
  'winding',
  'windy',
  'wobbly',
  'wooded',
  'wooden',
];

const superlatives = [
  'the best',
  'the biggest',
  'the brightest',
  'the calmest',
  'the cleanest',
  'the coldest',
  'the cutest',
  'the dumbest',
  'the least interesting',
  'the longest',
  'the loudest',
  'the most amazing',
  'the most anxiety-inducing',
  'the most anxious',
  'the most beautiful',
  'the most brilliant',
  'the most fearsome',
  'the most frustrating',
  'the most infuriating',
  'the most interesting',
  'the most nervous',
  'the most peaceful',
  'the most powerful',
  'the most predictable',
  'the most ridiculous',
  'the most ridiculous',
  'the most unbelievable',
  'the shabbiest',
  'the shiniest',
  'the sleepiest',
  'the smallest',
  'the smartest',
  'the softest',
  'the stupidest',
  'the sweetest',
  'the tallest',
  'the tiniest',
  'the warmest',
  'the weakest',
  'the worst',
];

const nouns = [
  'abbey',
  'aircraft carrier',
  'airplane',
  'alcove',
  'allegory',
  'alley',
  'altar',
  'alternate dimension',
  'amusement park',
  'anarchy',
  'apartment complex',
  'archaeological dig',
  'archipelago',
  'aristocracy',
  'assylum',
  'attic',
  'badminton court',
  'bakery',
  'balcony',
  'barn',
  'barrack',
  'barrel',
  'baseball field',
  'basement',
  'basket',
  'basketball court',
  'bathroom',
  'battlefield',
  'battleground',
  'battlezone',
  'bazaar',
  'beach',
  'beachhead',
  'bedroom',
  'beehive',
  'bin',
  'biplane',
  'blizzard',
  'bubble',
  'burger joint',
  'cabana',
  'cabaret',
  'cabin',
  'cabinet',
  'cafe',
  'cafeteria',
  'cage',
  'can of beans',
  'can of peas',
  'can of soup',
  'can',
  'cannery',
  'canyon',
  'car',
  'cardboard box',
  'carriage',
  'carrier',
  'castle',
  'cathedral',
  'cave',
  'cellar',
  'cemetary',
  'chamber',
  'chapel',
  'cinema',
  'cistern',
  'city',
  'classroom',
  'cliff',
  'cloud city',
  'cloud',
  'clown school',
  'cockpit',
  'colony',
  'compound',
  'computer screen',
  'concert hall',
  'corral',
  'correctional facility',
  'courthouse',
  'courtyard',
  'cove',
  'crater',
  'crawlspace',
  'crevasse',
  'crypt',
  'cubby',
  'cubbyhole',
  'cubicle',
  'cupboard',
  'cyberworld',
  'deck',
  'den',
  'department store',
  'desert',
  'dictatorship',
  'dictionary',
  'dimensional portal',
  'ditch',
  'dock',
  'doghouse',
  'dollhouse',
  'dormitory',
  'dream',
  'drugstore',
  'dugout',
  'dump',
  'dungeon',
  'electromagnet',
  'elevator',
  'encyclopedia',
  'erupting volcano',
  'ethernet cable',
  'farm',
  'farmhouse',
  'fish pond',
  'fishery',
  'flashback',
  'forest',
  'forge',
  'fort',
  'forum',
  'fountain',
  'freeway',
  'frontier',
  'funeral home',
  'furnace',
  'gallery',
  'garage',
  'garden',
  'garrison',
  'ghetto',
  'glacier',
  'grassland',
  'graveyard',
  'greenhouse',
  'grocery store',
  'grove',
  'guardhouse',
  'gulf',
  'gully',
  'gutter',
  'gym',
  'hall',
  'hallway',
  'hamlet',
  'hangar',
  'harbor',
  'hideaway',
  'hideout',
  'high school',
  'highway',
  'hill',
  'hospital',
  'hot tub',
  'hotel',
  'house',
  'hovel',
  'impact site',
  'improv studio',
  'inn',
  'island',
  'isle',
  'islet',
  'jail',
  'jukebox',
  'jungle',
  'junkyard',
  'kitchen',
  'laboratory',
  'labyrinth',
  'lagoon',
  'lake',
  'lavatory',
  'library',
  'living room',
  'locker room',
  'lodge',
  'lookout tower',
  'lounge',
  'madhouse',
  'mainframe',
  'mall',
  'maple tree',
  'market',
  'marketplace',
  'maze',
  'meadow',
  'mess of wires',
  'military base',
  'mine',
  'mineshaft',
  'monarchy',
  'monastery',
  'moon',
  'mosque',
  'motel',
  'mountain',
  'museum',
  'nest',
  'newsstand',
  'nightclub',
  'nursery',
  'oak tree',
  'ocean',
  'office',
  'orchard',
  'orphanage',
  'outpost',
  'pagoda',
  'palace',
  'palm tree',
  'parking lot',
  'party',
  'peninsula',
  'penthouse',
  'pet store',
  'pharmasy',
  'picnic',
  'pier',
  'pile of garbage',
  'pine tree',
  'pipeline',
  'piping system',
  'pit',
  'planetarium',
  'planetoid',
  'plateau',
  'platform',
  'playroom',
  'plaza',
  'police department',
  'pond',
  'poplar tree',
  'portal',
  'power cord',
  'power plant',
  'prison',
  'produce aisle',
  'pub',
  'pulpit',
  'purification chamber',
  'pyramid',
  'quarry',
  'racetrack',
  'railroad',
  'rehab center',
  'resort',
  'restaurant',
  'river',
  'road',
  'room',
  'rose bush',
  'runway',
  'salon',
  'saloon',
  'sawmill',
  'school',
  'sculpture',
  'seacoast',
  'sewer',
  'shack',
  'shop',
  'shower',
  'skyline',
  'speedboat',
  'stable',
  'stadium',
  'stage',
  'storehouse',
  'storeroom',
  'street',
  'studio',
  'suburb',
  'subway',
  'supermarket',
  'swamp',
  'synagogue',
  'telephone wire',
  'tollhouse',
  'tomb',
  'tower',
  'town',
  'trash can',
  'valley',
  'video game',
  'village',
  'vineyard',
  'volcano',
  'warehouse',
  'warzone',
  'wasteland',
  'windmill',
  'yard',
  'zeppelin',
];

import slugify from 'slugify';

export default function generateWordSlug() {
  const adjective = slugify(adjectives[Math.floor(Math.random() * adjectives.length)], { lower: true, strict: true });
  const superlative = slugify(superlatives[Math.floor(Math.random() * superlatives.length)], {
    lower: true,
    strict: true,
  });
  const noun = slugify(nouns[Math.floor(Math.random() * nouns.length)], { lower: true, strict: true });

  return `${superlative}-${adjective}-${noun}`;
}
